import { Container, Stack } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "تمام پست ها",
  description: "Generated by create next app"
};

export default function PostsLayout({
  children
}: Readonly<{ children: React.ReactNode }>) {

  return (
    <Container maxWidth={"sm"} sx={{ backgroundColor: "#f1f1f1"}}>
      <Stack height={"100vh"} flexDirection={"column"} justifyContent={"center"}>
      {children}
      </Stack>
    </Container>
  );
}
