import type { Metadata } from "next";
import { ThemeProvider } from "@/providers/ThemeProvider";
import ThemeRegistry from "@/theme";
import axios from "axios";
import {setupInterceptorsTo} from "@/config/axios";
import "@/assets/styles/globals.css";
import { IRANSansX } from "@/config/font";
import { SpeedInsights } from '@vercel/speed-insights/next';
import ReactQueryProvider from "@/providers/ReactQueryProvider"

setupInterceptorsTo(axios);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl" suppressHydrationWarning>
      <body className={IRANSansX.variable}>
        <ThemeProvider options={{ key: "css" }}>
          <ThemeRegistry>
            <ReactQueryProvider>
              {children}
            </ReactQueryProvider>
            <SpeedInsights />
          </ThemeRegistry>
        </ThemeProvider>
      </body>
    </html>
  );
}
