import { Container, Stack } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "پروفایل",
  description: "Generated by create next app"
};

export default function ProfileLayout({
  children
}: Readonly<{ children: React.ReactNode }>) {

  return (
    <Container maxWidth={"sm"} sx={{ backgroundColor: "#f1f1f1", padding: "16px" }}>
      <Stack height={"100vh"} flexDirection={"column"} justifyContent={"center"}>
        {children}
      </Stack>
    </Container>
  );
}